### ISSUE TITLE
Missing Files?

### ISSUE THREAD

**Issue by erik-r-peterson** [samuelneff/sequelize-auto-ts#10]
In linux, I'm trying to use this tool from the command line.

: npm install sequelize-auto-ts --save-dev

I'm having trouble doing that though. First, node doesn't know how to process typescript files. I'm not sure how the sample node lib\cli.ts ever works. I saw there's a cli.js file so that will run and there's a ts-node package which will allow running typescript from node. **Is this meant to run in typescript or is running the already-compiled js okay too?**

After getting the tool running, I get this error:

Error: ENOENT: no such file or directory, open '/var/tools/sequelize-auto-ts/lib/node.d.ts'

**The node.d.ts file isn't in the package. I'm not sure what to do. Is there something I'm doing wrong?**

Thanks.

**Comment by erik-r-peterson** [comment]
In case this helps here are my versions of npm and node, npm -v: 3.7.3, node -v : v5.9.1

**Comment by erik-r-peterson** [comment]
Dropping node.d.ts from another project into the lib directory made it generate. Perhaps it's just missing from the sequelize-auto-ts project?

**Comment by erik-r-peterson** [comment]
Using the version where all parameters are specified in the command line (as opposed to the interactive version), i get this similar error (after dropping node.d.ts in):

Error: ENOENT: no such file or directory, open '/var/tools/sequelize-auto-ts/lib/lodash.d.ts'

**Comment by samuelneff** [comment]
Run the already compiled `js` and you should be fine.

The `ts` files are there in case you want to run it from your own application, like when used from `grunt-sequelize-auto-ts`.
