### ISSUE TITLE
Does this generate model associations (belongsTo, hasMany, belongsToMany) from foreign keys?

### ISSUE THREAD

**Issue by NobleUplift** [samuelneff/sequelize-auto-ts#16]
I need a generator to create the foreign key relationships in my database because I'm doing it at runtime and it's taking too long in my application. Does this generator automatically create foreign key relationships?

**Comment by samuelneff** [comment]
This is a DB first generator. Given a database schema, it creates TypeScript interfaces and Sequelize code to create a corresponding model.
