### ISSUE TITLE
error TS2503: Cannot find namespace 'sequelize'

### ISSUE THREAD

**Issue by jfriv** [samuelneff/sequelize-auto-ts#4]
Hello Samuel!  I am new to Typescript and came across your project when looking for Typescript ORM examples.  I am super excited to potentially use your sequelize model generator for a larger project with an existing database.

I was able to successfully run:
`node lib/cli.js 'database' 'user' 'password' /path/to/src/models/ -mf` 
and can use the generated files in my target path.  I found that there is a newer version of `sequelize.d.ts` typescript definition, so I am attempting to use that rather than the one included in this repo.

While the generated models are functional, I am running into some errors when typescript compiles:

```
src/models/sequelize-model-factory.ts(16,15): error TS2503: Cannot find namespace 'sequelize'.
src/models/sequelize-model-factory.ts(21,22): error TS2503: Cannot find namespace 'sequelize'.
src/models/sequelize-model-factory.ts(26,76): error TS2503: Cannot find namespace 'sequelize'.
src/models/sequelize-model-factory.ts(55,42): error TS2339: Property 'find' does not exist on type 'lineModel'.
src/models/sequelize-model-factory.ts(70,91): error TS2503: Cannot find namespace 'sequelize'.
src/models/sequelize-models.ts(16,15): error TS2503: Cannot find namespace 'sequelize'.
src/models/sequelize-models.ts(19,22): error TS2503: Cannot find namespace 'sequelize'.
src/models/sequelize-models.ts(24,87): error TS2503: Cannot find namespace 'sequelize'.
src/models/sequelize-names.ts(27,14): error TS2300: Duplicate identifier 'lineFields'.
src/models/sequelize-names.ts(35,12): error TS2300: Duplicate identifier 'lineFields'.
src/models/sequelize-names.ts(35,36): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
src/models/sequelize-types.ts(40,39): error TS2503: Cannot find namespace 'sequelize'.
src/models/sequelize-types.ts(42,36): error TS2503: Cannot find namespace 'sequelize'.
src/models/sequelize-types.ts(43,20): error TS2503: Cannot find namespace 'sequelize'.
src/models/sequelize-types.ts(44,28): error TS2503: Cannot find namespace 'sequelize'.
```

I would really like to be able to compile without all these unsightly errors... I'm sure there is something simple I am doing wrong.

I've tried a few different things, but rather than bang my head on the keyboard, I figured I would ask for an example of how you are using the generated models in your projects.  Here is my app.ts file for reference:

```
/// <reference path="../typings/tsd.d.ts" />
/// <reference path="../typings/lodash/lodash.d.ts" />
/// <reference path="../typings/sequelize/sequelize.d.ts" />

import http = require('http');
import models = require('./models/sequelize-models');

var dbConfig = new databaseConfig.Config();
var models = new modelFactory.Models(dbConfig.database, dbConfig.user, dbConfig.password, dbConfig.options);
```

and here is a sample of one of the generated ts files, `src/models/sequelize-model-factory.ts`:

```
////////////////////////////////////////////////////////////////////
//
// GENERATED CLASS
//
// DO NOT EDIT
//
// See sequelize-auto-ts for edits
//
////////////////////////////////////////////////////////////////////

/// <reference path="../../typings/node/node.d.ts" />
/// <reference path="../../typings/sequelize/sequelize.d.ts" />

import types = require('./sequelize-types');

var Sequelize:sequelize.SequelizeStatic = require('sequelize');


export class Models {

    public SEQUELIZE:sequelize.Sequelize;

    public line:types.lineModel;
```

**Comment by AJamesPhillips** [comment]
Hey @feedthefire this is "fixed" in @honmaaax's fork (that I've included in [my fork](https://github.com/AJamesPhillips/sequelize-auto-ts/)).

**Comment by samuelneff** [comment]
@AJamesPhillips what exactly is fixed related to this issue? If `sequelize-auto-ts` can't find `sequelize.d.ts` in the target project then it'll copy it over. In either case, it should set the relative path in the generated file so TypeScript resolves `sequelize` references. Is that not working in some situations? From the above code it appears to have worked since the relative path is different from what I have (unless it was manually edited).

I reviewed some of the forks and I think what I saw was more than just bug fixes, but some behavioral changes.

**Comment by AJamesPhillips** [comment]
Hey @samuelneff,

I have updated previous comment to say "fixed".  @feedthefire was trying to upgrade to the latest version of sequelize who's corresponding `.d.ts` file defines `declare module "sequelize" { ... }` which for reasons I'm not yet clear on means you also have to have `import sequelize = require('sequelize');` to satisfy TypeScript.  See my related question on SO:  http://stackoverflow.com/questions/35228216/typescript-not-finding-definitions

I think you can close this issue.
