### ISSUE TITLE
Support PostgreSQL

### ISSUE THREAD

**Issue by AJamesPhillips** [samuelneff/sequelize-auto-ts#6]
I'll try to follow your advice on [this issue](https://github.com/samuelneff/sequelize-auto-ts/issues/5) and shout if I run into problems.  First version will be _very hacky_ as under a similar time squeeze so please bear with me :smile:

**Comment by AJamesPhillips** [comment]
I notice the files have cr at eol so will try to maintain them (am using:  `git config core.whitespace cr-at-eol`, hope that's correct).

**Comment by bykbtzr** [comment]
Maybe it's worth to make changes against [honmaaax's fork](https://github.com/honmaaax/sequelize-auto-ts).

**Comment by AJamesPhillips** [comment]
Good call @cvsguimaraes, thanks.

I think I'm going to pause this soon though as there a lot of ground to cover with the code and we need to get some tests in there first.

Perhaps @samuelneff could help me out with a couple of points though.  First one is how processIdFields determines id fields.  If you have a table with a primary key on a field called `id`, it "falls foul" of [this test](https://github.com/samuelneff/sequelize-auto-ts/blob/942506ed6059c830d63b681855c66ad93adee278/lib/schema.ts#L792).  I have changed this conditional in the branch I'll push up here.   Was wondering if you had done any development on better methods of determining id fields, like the presence of primary or compound key?

For what it's worth, I'm refactoring the code to work with my migrations (rewritten in MySql) first and having various errors.  I will work on PostgreSQL later, so should probably open the other errors/questions as separate issues.  Happy to do that.  *\* **edit** *\* have open one here:  https://github.com/samuelneff/sequelize-auto-ts/issues/7
