### ISSUE TITLE
A primary key field called `id` is not counted as an id field

### ISSUE THREAD

**Issue by AJamesPhillips** [samuelneff/sequelize-auto-ts#7]

**Comment by samuelneff** [comment]
Yes, `sequelize-auto-ts` is very opinionated (as am I). `id` is not something I'd consider a proper id field. Should be more descriptive.

Nonetheless, if you want to submit a PR that fixes this issue, I'll merge.

**Comment by AJamesPhillips** [comment]
No that's fine, I'll close this issue.

**Comment by a-lucas** [comment]
@samuelneff 
Why in your opinion id is NOT a proper id field?

For example: user.id
it means user's id
IMHO, If a table doesn't describe correctly the content: let's say someone named the `niceCar` table `NC`, sure `NC.id` would not give much sense, but folloing your logic,  `NC.NcId` wouldn't help too.

Can you please give me a usage scenario where a table's  primary key is used in code where the table is nowhere to be referenced next to it?

Maybe in SQL queries, if you start using aliases, like `niceCar as NC`, then of course, later on in your (super long SQL query), you would have `NC.id`, but you could also have `niceCar.id` and remove the alias.

I know this is opinion, but I believe opinion war is useless, while opinion explanation is a step to progress.

**Comment by samuelneff** [comment]
Thanks for asking the way you did. I'll be happy to explain, and as you said, it's just my opinion.

I'm very much against aliasing fields. If you use `id` for all of your primary keys then you have to alias them every time you join two tables and return more than one id.

You also necessarily end up with foreign keys that don't match the primary key name which I dislike. A join like 'Orders.userId = Users.id" is not something I like to see, typically I do alias all tables so it'd be "O.userId = U.id" which can lend itself to errors more easily.

While it's certainly possible to use `id` for all primary keys and many people do, in my 22 years of experience I've found it better to use unique field names across the entire database for all fields.

Sam

**Comment by AJamesPhillips** [comment]
@a-lucas, thank you too for adding the last sentence.  I should have asked this long ago.  Thank you too very much @samuelneff for the explanation, including use cases, common sources/routes of errors.  I have changed my opinion on this issue.  Thank you.
