### ISSUE TITLE
Not all fields will be evalulated

### ISSUE THREAD

**Issue by AJamesPhillips** [samuelneff/sequelize-auto-ts#8]
I'm not certain because I have yet to run the code but from looking at: https://github.com/samuelneff/sequelize-auto-ts/blob/master/lib/sequelize-types.ts#L62-L69 I think only the fields the pojo object has will be assessed, but what you want is to assess all the fields expected on the models too.  Something like:  `_.unique(fieldNames.concat(modelFieldNames))`.

**Comment by samuelneff** [comment]
What fields are in the models (instance?) that are not in the pojo? If they're calculated/generated fields added in `define`, then they would not want to be validated.

Perhaps I'm misunderstanding what you're saying...?

**Comment by AJamesPhillips** [comment]
No, makes sense.  Apologies for the noise.
